#cloud-config
users:
  - name: web
    primary_group: web
    groups: wheel
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPYnqx8wdhZ/xOyc/LG12cOydkrEBhUev8R/bPzESWSX herman@ZBF-13

packages:
  - nginx
  - nmap